#!/bin/bash

export OPENLANE_ROOT=/opt/openlane
export OPENLANE_PDK=/opt/dk_volare
export PDK_ROOT=/opt/dk_volare
export PDK=sky130A
# export PDK=gf180mcuC

conda deactivate
source ./venv/bin/activate

